### ISSUE TITLE
Tomahawk throws TLS Error

### ISSUE THREAD

**Issue by guiweber** [guiweber/just-install-updater#4]
Their new certificate is now up on their website but node still throws an error: UNABLE_TO_VERIFY_LEAF_SIGNATURE... maybe the CA (lets encrypt) is not fully supported in the latest node version or maybe it is a config error on their end. Lets wait and see if it resolves itself over the next few weeks.

**Comment by Schokobecher** [comment]
Here is my workaround:

Install [ssl-root-cas](https://github.com/Daplie/node-ssl-root-cas) into your jiup directory:
`npm install ssl-root-cas`

This package contains many intermediary certificates that browsers trust but node doesn't.

Add the following to your `jiup.js`:

> require('ssl-root-cas/latest')
>   .inject()
>   .addFile(__dirname + '/letsencrypt.crt');

Put the attached Let's Encrypt crt into the root of the folder, run jiup and let it gather all the necessary certificates. Voila!
[letsencrypt.zip](https://github.com/guiweber/just-install-updater/files/676158/letsencrypt.zip)

**Comment by guiweber** [comment]
Thanks, I'll look into implementing this. Where did you take the certificate from?

**Comment by Schokobecher** [comment]
I grabbed the Let'sEncryptAuthorityX3 crt from their webseite using firefox

**Comment by guiweber** [comment]
Thanks, done and done!
