### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Schokobecher** [guiweber/just-install-updater#6]
I'm trying to implement an Opera version extractor and ran into a brick wall.

My entry looks like this:

>     "opera": {
>     "url": "https://www.opera.com/download/guide/?os=windows",
>     "updater": {
>       "x86":{
>         "rule_type": "css-html-version",
>         "selector": "h3.version",
>         "baselink": "https://download4.operacdn.com/pub/opera/desktop/{{.version}}/win/Opera_{{.version}}_Setup.exe"
>       }
>     },
>     "version_extractor": "([.\\d]+[.]\\d{1,99})"
>     "version_extractor_alt":"\\d{1,3}\\.?\\d{1,3}(?:\\.\\d{1,4}\\.\\d{1,4})?"
>   }

and I get the following output:

> Fetching data..opera x86: Processing css-html-version rule on data from http://www.opera.com/download/guide/?os=windows
> opera x86: Found 1 CSS selector matches
> opera x86: Found link https://download4.operacdn.com/pub/opera/desktop/41.0.2353.46/win/Opera_41.0.2353.46_Setup.exe
> opera x86: Found version: 41.0.2353.46
> 
> Updating opera x86
> Web: v.41.0.2353.46 https://download4.operacdn.com/pub/opera/desktop/41.0.2353.46/win/Opera_41.0.2353.46_Setup.exe
> Reg: v.undefined http://www.opera.com/download/get/?id=40225&location=410&nothanks=yes&sub=marine
> C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\helpers.js:14
>   curVer = curVer.split('_').join('.');
>                  ^
> 
> TypeError: Cannot read property 'split' of undefined
>     at Object.exports.isVersionNewer (C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\helpers.js:14:18)
>     at update (C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\jiup-lib.js:469:28)
>     at parseAll (C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\jiup-lib.js:201:7)
>     at oneDone (C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\jiup-lib.js:507:5)
>     at IncomingMessage.res.on (C:\Users\Schok\Documents\GitHub\jiupdater-private\just-install-updater\jiup-lib.js:162:9)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

The link works fine, did I break it? I bet it's related to Operas crazy .exe naming scheme.

Related herlper.js code:

> //Attempts to determine if the web version is newer than the registry version.
> //At the moment, letters are ignored.
> exports.isVersionNewer = function(curVer, newVer){
>   curVer = curVer.split('_').join('.');
>   newVer = newVer.split('_').join('.');
>   if(cv(newVer, curVer) == 1){
>     return true;
>   }else{
>     return false;
>   }
> }

**Comment by guiweber** [comment]
I'll leave this issue open to remind me to implement a appropriate error message for this kind of situation. I believe the issue has something to do with the fact that the just-install registry has no numeric version defined for Opera.

The Just-Install registry has a permanent link to the latest version of Opera, and the version field is defined as "latest". So there is actually no need to put an update rule in place for Opera : )

**Comment by Schokobecher** [comment]
Oh that makes sense.
Maybe `-todo` should also check for `latest` in the registry, because Opera is currently listed (should have checked the registry file though). Is `latest `preferred over knowing the exact version number?

**Comment by guiweber** [comment]
`-todo` does check for `latest`, which made me figure out the issue : )

So the reason for the crash and why it is showing up in `-todo` is that the just-install registry is malformed. The `version` field is placed under `installer` but it should be placed at the root of the entry!

I'll make the modification in the registry.

**Comment by guiweber** [comment]
P.S. also be aware that some legacy apps, such as python 2.6 and 2.7, showed in the todo list do not need an updater rule because lvillani need those specific version in just-install. I need to add a flag to those so they can be ignored, but it's not implemented yet. So anything that looks quite old and is related to programming is best left untouched for now. Cheers!
