### ISSUE TITLE
Archiving the repo

### ISSUE THREAD

**Issue by lvillani** [guiweber/just-install-updater#67]
@guiweber @cyagon @geek1011 Would you mind if I archive this repository, now that https://github.com/just-install/just-install-updater-go is fully working?

**Comment by pgaskin** [comment]
Yep. I will also disable the periodic Travis builds once this repo is archived.

Also, I haven't seen @guiweber and @cyagon here for a while.

**Comment by lvillani** [comment]
I'm letting a week go by to allow for further comments, then archive it if no one has an objection.

**Comment by lvillani** [comment]
Archiving now! 📦
